psychopy/psychojs

- js/psychojs/data.js
add psychoJS support for nReps and
sequential/random/fullRandom trial sequences.
Add columns from conditions files to data output.
Make loops marked as “isTrials” cause a data line
to be written each iteration. Add an “eventName”
column to the data file to identify whether a data
line was caused by a keyboard event or a loop iteration.
write out experiment data when quitPsychoJS() is called.
This commit goes with the one with the same name in the
psychopy project
> nReps and sequential/random/fullRandom

- js/util/Util.js
Added Blink detection (from snippet at https://stackoverflow.com/a/9851769)
> Add Blink detection

- js/core/MinimalStim.js
- js/visual/ImageStim.js
- js/visual/MovieStim.js
- js/visual/ShapeStim.js
- js/visual/TextStim.js
> core/MinimalStim: add release method

- js/core/GUI.js
@peircej @apitiot In line with OS dialog boxes, put "OK" button last. Closes #115?
> core/GUI: swap placement of OK/Cancel dialog box buttons

- js/visual/ImageStim.js
> visual/ImageStim: fix JSDoc typo

- js/data/TrialHandler.js
@peircej @apitiot Clean up #95. Closes psychopy/psychopy#2299?
Demo:
http://didactic-belief.surge.sh
> data/TrialHandler: PR#95 follow up decoding .csv conditions imports

- js/core/GUI.js
@apitiot @peircej Closes #118?
> core/GUI: give the OK button focus if enabled

- js/core/PsychoJS.js
> Give the PsychoJS.start() expInfo option a default value

- js/util/Util.js
> Return selection as an array of arrays

- js/core/GUI.js
> core/GUI: Make jQuery UI dialog boxes non-draggable, non-resizable

- js/sound/TonePlayer.js
> sound/TonePlayer: call toMaster on volumeNode if toDestination missing

- js/visual/MovieStim.js
@apitiot Closes #235 
Demo:
[run.pavlovia.org/thewhodidthis/movie-loop &rarr;](https://run.pavlovia.org/thewhodidthis/movie-loop/)
> visual/MovieStim: add loop attribute

- js/visual/TextStim.js
> visual/TextStim: fix jsdoc for alignHoriz

- js/visual/ShapeStim.js
> visual/ShapeStim: set closeStroke on PIXI polygon creation

- js/visual/TextInput.js
> visual/TextInput: replace for...in with a forEach loop

- js/core/Keyboard.js
- js/core/Mouse.js
- js/core/ServerManager.js
- js/core/Window.js
- js/data/ExperimentHandler.js
- js/data/TrialHandler.js
- js/sound/Sound.js
- js/sound/TonePlayer.js
- js/sound/TrackPlayer.js
- js/util/PsychObject.js
> core/data/sound/util: drop PsychObject._addAttributes() and refs thereof

- js/visual/ShapeStim.js
> visual/ShapeStim: take contrast into account when calling beginFill

- js/data/ExperimentHandler.js
@peircej @apitiot Closes #124?
> data/ExperimentHandler: remove duplicate isEntryEmpty method

- js/visual/MovieStim.js
> visual/MovieStim: do tell PIXI base texture to respect autoplay

- js/data/TrialHandler.js
> data/TrialHandler: add FULLRANDOM alias to mirror PP output

- js/data/TrialHandler.js
- js/util/Util.js
@apitiot Closes #205
Test:
[gist.github.com/thewhodidthis/95637b6a4d406900b5650111ac9a5446 &rarr;](https://gist.github.com/thewhodidthis/95637b6a4d406900b5650111ac9a5446)
Demo:
[run.pavlovia.org/thewhodidthis/animated-text &rarr;](https://run.pavlovia.org/thewhodidthis/animated-text/)
> Allow for parsing of array-like strings when setting visual stimulus position or size

- js/visual/ImageStim.js
@apitiot Roll back a few edits brought in with #261, closes #283
Demo:
[run.pavlovia.org/support/echo &rarr;](https://run.pavlovia.org/support/echo/)
> visual/ImageStim: tweak texture related PIXI calls

- js/visual/Slider.js
> visual/Slider: estimate bounding box at the top of update calls

- js/sound/TrackPlayer.js
@apitiot Closes #294, please note the default duration of roughly 1 / 60 secs
> sound/TrackPlayer: add fades on play / stop

- js/visual/ImageStim.js
> visual/ImageStim: check if image attribute different before onChange() call

- js/visual/Form.js
@RebeccaHirst @apitiot closes #280
Demo:
[run.pavlovia.org/thewhodidthis/forms &rarr;](https://run.pavlovia.org/thewhodidthis/forms)
> visual/Form: support the radio type, same as choice

- js/sound/Sound.js
@peircej @apitiot Implement a `setSound(sound, log)` method for dynamically updating the current value. What do you think about returning `this` to allow for chaining? Closes #132?
> sound/Sound: add setSound method

- js/core/Keyboard.js
> core/Keyboard: re-allow default behaviour on keydown

- src/visual/ButtonStim.js
- src/visual/TextBox.js
- src/visual/TextInput.js
- src/visual/index.js
@apitiot Closes #316 
Demo: [pavlovia.org/thewhodidthis/button &rarr;](https://pavlovia.org/thewhodidthis/button)
> Implement ButtonStim class

- src/data/ExperimentHandler.js
@peircej @apitiot Closes #290
Demo: [pavlovia.org/thewhodidthis/bomified &rarr;](https://pavlovia.org/thewhodidthis/bomified)
> data/ExperimentHandler: prepend BOM when exporting CSV

- CONTRIBUTING.md
> DOCS: update contributing guide to reflect default branch is now main

- src/visual/Form.js
- src/visual/Slider.js
- src/visual/TextBox.js
@apitiot @TEParsons Closes #315
Demo:
[pavlovia.org/thewhodidthis/colorful-bfi &rarr;](https://pavlovia.org/thewhodidthis/colorful-bfi)
> visual/Slider/Form/TextBox: towards implementing five color model

- src/sound/TrackPlayer.js
> sound/TrackPlayer: drop extra play / seek calls

- scripts/build.js.cjs
@peircej @apitiot @tpronk Closes #360
> scripts/js: add an iife outfile with PsychoJS global

- scripts/build.js.cjs
> scripts: add sourcemap option for esbuild

- scripts/build.js.cjs
> scripts: override esbuild default target

- package-lock.json
> git/npm: tweak lock file

- package-lock.json
- package.json
- src/core/ServerManager.js
> Remove PreloadJS dependency

- src/visual/TextInput.js
@apitiot Closes #318 
Demo:
[pavlovia.org/thewhodidthis/textbox-borderless &rarr;](https://pavlovia.org/thewhodidthis/textbox-borderless)
> visual/TextInput: use nullish coalescing operator for stroke styling fallbacks

- src/visual/TextInput.js
@RebeccaHirst @apitiot Echoes https://github.com/Mwni/PIXI.TextInput/issues/4, closes #377 and closes #341 
Demo:
[pavlovia.org/support/textbox-scroll-bug &rarr;](https://pavlovia.org/support/textbox-scroll-bug)
> visual/TextInput: permanently disable substitute text

- src/visual/Slider.js
@apitiot @RebeccaHirst Closes #322 
Demo:
[pavlovia.org/thewhodidthis/slider &rarr;](https://pavlovia.org/thewhodidthis/slider)
> visual/Slider: provide fillColor aliases for markerColor

- src/visual/TextBox.js
- src/visual/TextInput.js
> visual/TextBox/TextInput: only disable text substitution when multiline

- src/visual/Slider.js
@apitiot @TEParsons Closes #401 
Demo:
[pavlovia.org/thewhodidthis/slider &rarr;](https://pavlovia.org/thewhodidthis/slider/)
> visual/Slider: add lineColor option, borderColor alias

- src/visual/TextBox.js
@apitiot @TEParsons Closes #404 
Demo:
[pavlovia.org/thewhodidthis/button-395 &rarr;](https://pavlovia.org/thewhodidthis/button-395/)
> visual/TextBox: add clear method, tweak reset to take editable into account

- src/visual/Form.js
@apitiot @RebeccaHirst Closes #329 
Demo:
[pavlovia.org/thewhodidthis/forms &rarr;](https://pavlovia.org/thewhodidthis/forms/)
> Do support Form.Types.SLIDER

- scripts/build.js.cjs
> scripts: tweak js minification options to leave identifiers as is

- src/core/ServerManager.js
- src/sound/AudioClip.js
- src/sound/AudioClipPlayer.js
- src/sound/Microphone.js
- src/sound/TrackPlayer.js
- src/visual/MovieStim.js
And JSON resources are now correctly imported. Fixes #421
> added more features to AudioClip and AudioClipPlayer

- src/core/ServerManager.js
> core/ServerManager: do import Clock

- src/core/GUI.js
- src/index.css
@apitiot Closes #209 and closes #210
Demo:
[pavlovia.org/thewhodidthis/forms &rarr;](https://pavlovia.org/thewhodidthis/forms)
> core/GUI: clean up dialog pane sizing parts, use css

- src/core/PsychoJS.js
- src/core/ServerManager.js
- src/data/ExperimentHandler.js
- src/data/MultiStairHandler.js
- src/data/QuestHandler.js
- src/data/TrialHandler.js
- src/util/Util.js
- src/visual/VisualStim.js
MultiStairHandler now produces experiment data in line with those produced by PsychoPy
> FF completed the information available in the experiment data for MultiStairHandler

- src/visual/TextStim.js
- src/visual/VisualStim.js
I also took that opportunity to clean up TextStim and VisualStim comments.
> BF: issue with bounding box estimation for TextStim

- src/visual/Slider.js
Starting val doesn't appear online from Bugs with slider online series.
> Starting val doesn't appear online

- src/visual/GratingStim.js
- src/visual/ImageStim.js
Created to cover next possible request for [CU-2hcbxjf] https://app.clickup.com/t/2hcbxjf
> Interpolation support for ImageStim and solution for shared resources

- src/visual/GratingStim.js
- src/visual/shaders/radialShader.frag
First approach to generate radial stimuli.
> Radial stim generation in shaders;

- src/util/Util.js
Add a basic function for the equivalent of np.linspace online
> add linspace to util.js

- src/visual/Progress.js
- Proper use of `_pixi.drawRect()` method.
- Implementation of `_estimateBoundingBox()` to cover window resize scenarios.
> Progress bar bugfix.
