- js/psychojs/events.js
The KeyboardEvent.keyIdentifier and .keyCode attributes
have been deprecated. the .keyIdentifier attribute has
been replaced by the .key attribute.
Change keyDownHandler to use non-deprecated attributes
KeyboardEvent.code and KeyboardEvent.key.
Change getKeys to use these attributes to identify
which key was pressed.
keyList argument passed to getKeys can contain both
key codes, e.g. "KeyM" and "Space" and key values,
e.g. "m" and " ".
> Use non-deprecated KeyboardEvent attributes

- js/psychojs/events.js
Make keyDownHandler and getKeys give preference to
the use of the W3C standard keyboardEvent.code for
identifying keys pressed. The deprecated .keycode
attribute is still honored to allow older browsers
that do not support the .code attribute.
the keyList argument to getKeys should consist
of pyglet key names, allowing scripts created
using the builder to work in web experiments.
> Modify getKeys to use most pyglet keynames

- js/visual/Rect.js
Related to https://github.com/psychopy/psychojs/issues/44 point 2. This
fix allows users to call setSize to change rect size, as with Python code.
To change rect size, the setSize method calls the setWidth and
setHeight methods of Rect stim.
> BF: Add setSize method to Rect

- js/visual/Slider.js
As noted in this discourse post:
https://discourse.psychopy.org/t/slider-setreadonly-sets-contrast-incorrectly/7055
Also, I wonder if we should be changing contrast by halving the color
values (if they are signed color vals) rather than the transparency, in
keeping with the Python version. Transparency will be weird if the scale
is on a textured backgorund?
> Fix: setReadOnly(false) was having no effect

- .editorconfig
The indentation in JS and HTML looks wrong because of GitHubs default
settings (I think is 8 spaces for an indent?). This .editorconfig file
allows us to define what indentation params should be used for specific
file types, making the JS more readable and consistent with code style
convention.
> ENH: adds .editorconfig file to repo

- js/visual/Slider.js
@apitiot @peircej Insert a `refresh()` method into the `Slider` component to switch on the `_needVertexUpdate` property so that resizing the `Window` properly reflects on instance position.
Issue #53 preview:
https://pavlovia.org/run/dvbridges/sliderradio/html/
With fix applied:
http://synonymous-balloon.surge.sh
Issue #83 preview:
https://run.pavlovia.org/dvbridges/test_slider/html/
With fix applied:
http://silky-friend.surge.sh
> visual/Slider: override refresh method a-la ShapeStim

- js/visual/ImageStim.js
- js/visual/MovieStim.js
- js/visual/ShapeStim.js
- js/visual/TextStim.js
@peircej @apitiot Add guards against memory leaks as described in #97, possibly addresses #77 as well.
> Call destroy on internal _pixi instance across visual stimuli

- js/util/Util.js
@peircej @apitiot Helpers added for `sum()` and `round()`. Closes #128?
Spec:
https://gist.github.com/thewhodidthis/134950d285df2da12142786dddc013f3
> util/Util: add Crib Sheet math extras

- js/visual/VisualStim.js
Align handling of orientation values with the desktop version turning positive angles into clockwise rotations.
Preview:
[simplistic-stick.surge.sh](http://simplistic-stick.surge.sh)
@apitiot Closes #87? @peircej CSS transforms work like PsychoPy's.
> visual/VisualStim: flip rotations to reflect psychopy convention

- css/psychojs.css
@apitiot @peircej Just a tiny CSS fix, should work unprefixed down to IE11, closes #101?
> css: center root pseudo message using tranform/translate

- js/core/Mouse.js
@apitiot @peircej Implement `Mouse.isPressedIn()` with a slightly different signature to PsychoPy when it comes to targeting a specific button. Closes #104?
Demo:
http://succinct-harbor.surge.sh
> core/Mouse: add isPressedIn method

- js/core/Window.js
@peircej @apitiot When closing the PsychoJS window, it appears destroying the internal renderer ahead of losing context was the cause of the problem. Closes #116?
[gitlab.pavlovia.org/thewhodidthis/testmovie2/tree/bf#116--movie](https://gitlab.pavlovia.org/thewhodidthis/testmovie2/tree/bf%23116--movie)
> core/Window: lose gl extension context before PIXI renderer

- js/visual/MovieStim.js
@peircej @apitiot  Have `MovieStim.seek()` try setting `currentTime` on the underlying `this._movie` video element if `fastSeek()` is unavailable and DRY up `stop()` and `reset()` accordingly. This should provide better browser support, but issue #133 could also be due to PsychoPy generated JS code lacking `reset()` calls when initiating new trials (in a loop).
Demo in which movie playback will reset once nine seconds in:
http://lacking-shoe.surge.sh
> visual/Movie: add currentTime fallback when video seeking

- js/util/ColorMixin.js
@peircej @apitiot Have `ColorMixin` reflect that for visual components like `TextStim` changing 'color' and 'contrast' attributes [needs PIXI related calls](psychopy/psychojs/blob/master/js/visual/TextStim.js#L306). The same result can be achieved as shown below, but simply setting `this._needPixiUpdate = true;` requires no checks. Closes #148?
```js
if (typeof this._onChange === 'function')
{
this._onChange(true, false)();
}
```
> util/ColorMixin: force a PIXI update when setting color or contrast

- js/visual/MovieStim.js
@peircej @apitiot A JS only workaround to avoid flashing of frames when playing movies in repeat over multiple trials. Please find a test case fork also highlighting a couple of code generation bits potentially off balance below,
https://gitlab.pavlovia.org/thewhodidthis/testmovie2
Closes #133 and closes #140?
> visual/MovieStim: DOM clone video baseTexture during setMovie call

- js/visual/MovieStim.js
@apitiot It appears 6e8f3bf612f5895afbd243098bcdb83c1260fe0c edits in the handling of argument defaults in class constructors left out 'interpolation' for `MovieStim`, closes #150
> visual/MovieStim: add interpolate when destructuring options on init

- js/visual/MovieStim.js
@apitiot @peircej Destroy main texture and children, but leave baseTexture untouched, closes #142?
> visual/MovieStim: tweak options when destroying pixi sprite

- js/sound/Sound.js
- js/sound/TonePlayer.js
- js/sound/TrackPlayer.js
@apitiot @peircej This would be one way of having Howler.js adjust the duration of the default sprite that gets created when initialising the player for an audio resource during the download process. The Tone.js based `TonePlayer` class already offers this type of setting.
Please note that for both players setting playback duration is actually available through `setSecs()` on a `Sound` instance. Also, while the `stopTime` attribute remains unchanged, it does end up getting ignored in practice when the duration is set after first creating a `Sound` object. Closes #131?
> sound/TrackPlayer: add setDuration()

- js/visual/MovieStim.js
@apitiot Checking if `this._size` is undefined and completely forgetting the then unused `size` variable would be another option. Closes #157?
> Tweak MovieStim._estimateBoundingBox() to use a _getDisplaySize based variable instead of _size

- js/sound/TonePlayer.js
@apitiot As it happens, the `triggerRelease()` call as part of `TonePlayer.stop()` needs a note value argument to run smoothly, same as `triggerAttackRelease()` inside of `playToneCallback()`. Closes #155.
> sound/TonePlayer: fix triggerRelease

- js/data/TrialHandler.js
- js/util/Util.js
@peircej @apitiot The problem here was an attempted destructuring assignment inside of `TrialHandler.importConditions()`. Please note that, like before, if a cell is found to contain more than one array looking substrings, [only the first match is kept](https://github.com/thewhodidthis/psychojs/blob/bf%23165--data/js/data/TrialHandler.js#L481). Closes #165?
> data/util: Have util export turnSquareBracketsIntoArrays, fix when called inside of importConditions

- js/util/Util.js
@apitiot It appears that going through `this._gui.dialog()` for error display can be avoided in this case? Closes #189
> util/Util: tweak toNumerical error throwing to not rely on this._gui

- js/core/GUI.js
@apitiot As documented [on discourse](https://discourse.psychopy.org/t/pavlovia-phaser3-tips-for-writing-data/16238/8) when using PsychoJS sans GUI on the server, closes #193 
Problem: [run.pavlovia.org/thewhodidthis/study-game-1 &rarr;](https://run.pavlovia.org/thewhodidthis/study-game-1/)
No problem: [run.pavlovia.org/thewhodidthis/download-resources-not &rarr;](https://run.pavlovia.org/thewhodidthis/download-resources-not/)
> core/GUI: make sure _setRequiredKeys exists before accessing its size

- js/visual/ImageStim.js
@apitiot Like #158 but for `visual.ImageStim`, closes #176.
> visual/ImageStim: tweak _estimateBoundingBox() to use size over this._size

- js/util/Util.js
@apitiot Rework what happens when the selection argument is an array, closes #197 and closes #200
> util/Util: fix selectFromArray() to respect selection order

- js/visual/TextBox.js
@apitiot Because when editable, reading the `TextBox.text` attribute will only return the initial value. Closes #159 and closes #160?
> visual/TextBox: Add methods for accessing the underlying input text

- js/visual/MovieStim.js
@apitiot Not that the script won't run as is, but upgrading to PixiJS latest, as required to fully address #168, does log a console error without this, closes #169 and closes #184.
> visual/MovieStim: deal with promise based video play

- css/psychojs.css
- js/core/PsychoJS.js
@apitiot Because pseudo elements are unavailable via DOM selectors, this is one relatively simple way of hiding `#root::after` by giving it an `.is-ready` class via jQuery, which is then defined in CSS, closes #175 
Demo: [run.pavlovia.org/thewhodidthis/blank &rarr;](https://run.pavlovia.org/thewhodidthis/blank/)
> Do hide the "Initialising the experiment..." message on PsychoJS init

- js/util/Util.js
@apitiot Closes #206 by way of amending `toNumerical()` to type coerce string input into its numerical form flat instead of inside of an array
Test: https://gist.github.com/thewhodidthis/95637b6a4d406900b5650111ac9a5446
> util/Util: tweak toNumerical() to match JSDoc comment

- js/util/Util.js
@apitiot Rely on [`String.prototype.match()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#Browser_compatibility) instead of `matchAll()`, closes #226
> util/Util: fix turnSquareBracketsIntoArrays for older browsers

- js/core/Window.js
- js/visual/MovieStim.js
@peircej @apitiot Upgrading to [PixiJS 5.3.3](https://github.com/pixijs/pixi.js/releases/tag/v5.3.3) seems necessary to address our video playback issues. This PR includes post upgrade edits required on our end, most importantly giving `autoDetectRenderer` a width and height as part of the options object instead of as separate arguments. Closes #168, but again is meant to be applied in combination with a PixiJS version bump :blush:
In action:
(a) [Start playing without having to wait &rsaquo;](https://run.pavlovia.org/thewhodidthis/multiplemovie)
(b) [Seamless repetition &rsaquo;](https://run.pavlovia.org/thewhodidthis/testmovie2/)
> Post PIXI upgrade tweaks

- js/core/GUI.js
- js/sound/TonePlayer.js
@peircej @apitiot Closes #211 provided [HTML boilerplate links to Tone.js latest](https://github.com/psychopy/psychopy/pull/3219), please note [the Tone.start() call](https://github.com/psychopy/psychojs/pull/212/files#diff-7bec8787bd851c93410746673590e3ad4405e8af797869569084ede5adb7d89bR270) as part of GUI's OK button click handler. Demo: [run.pavlovia.org/thewhodidthis/chromatic &rarr;](https://run.pavlovia.org/thewhodidthis/chromatic/)
> Post Tone.js upgrade tweaks

- js/visual/TextBox.js
@apitiot Allows for turning the underlying `TextInput` DOM element into a `<textarea>`, which may then accept height adjustments. Closes #220 and closes #191
> visual/TextBox: expose multiline property

- js/visual/TextBox.js
- js/visual/TextInput.js
@apitiot @RebeccaHirst Give the first available TextBox instance focus unless the _autofocus_ option is false, closes #270 
Demo:
[run.pavlovia.org/thewhodidthis/textbox-autofocus &rarr;](https://run.pavlovia.org/thewhodidthis/textbox-autofocus)
> visual/TextBox: implement autofocus

- js/core/Keyboard.js
@apitiot Closes #167, the issue seems gone on Safari latest anyways
Demo:
[run.pavlovia.org/thewhodidthis/beeping-not &rarr;](https://run.pavlovia.org/thewhodidthis/beeping-not/)
> core/Keyboard: prevent default on keydown

- js/visual/Slider.js
@apitiot Closes #69? Font size is no hidden attribute, a setter is available just like any other attribute. Label height on the other hand has no PsychoPy equivalent and is currently used nowhere in the script 😊
> visual/Slider: drop unused labelHeight attribute

- js/core/Window.js
- js/util/Scheduler.js
@apitiot Calculate FPS with every rAF call, closes #257 and closes #199 
Demo:
[run.pavlovia.org/thewhodidthis/rolling-fps-meter &rarr;](https://run.pavlovia.org/thewhodidthis/rolling-fps-meter)
> Implement Window.getActualFrameRate() to dynamically update monitorFramePeriod

- js/core/PsychoJS.js
@apitiot Closes #230 
Demo:
[pavlovia.org/thewhodidthis/extra-config-hosts &rarr;](https://pavlovia.org/thewhodidthis/extra-config-hosts)
> core/PsychoJS: enable whitelisting of config.json hosts

- js/data/TrialHandler.js
@RebeccaHirst Closes #246, @apitiot please let me know if you would like to see a separate helper in Util. Please note that Alt + Enter may always be used to encode line feeds in .xlsx files instead of '\n'
> data/TrialHandler: allow for doubly escaped LFs in xlsx cells

- js/core/GUI.js
@apitiot As @bbonf points out, some versions of Win / Edge still in use fail to recognise `CSS.escape()`. One option would be to go back to using `jQuery.escapeSelector()`. Or, as shown here, we could do away with sanitising dictionary keys in `GUI.DlgFromDict()` and rely on plain indices for deriving the _id_ and label _for_ form input attributes. I have checked and these references are only found within that one method. Closes #215?
Demo:
[run.pavlovia.org/thewhodidthis/css-escape-not &rarr;](https://run.pavlovia.org/thewhodidthis/css-escape-not)
> core/GUI: refactor CSS naming of dialog box input elements

- .gitignore
- package-lock.json
- package.json
- src/core/PsychoJS.js
This PR contains the following changes:
* **d92d875 Prefix cross-var with npx, so it runs in GitHub.** The cross-var package adapts npm environment variables to the right format for bash (`$npm_package_version`) and Windows (`%npm_package_version%`). I have added the cross-var package and accidentally committed it directly to PsychoJS. This change prefixed calls to cross-var with npx, so that it also works in GitHub Actions.
* **9c28f51 Write captured errors to body.data-report attribute.** When a wdio test fails, it looks in document.data-error whether any JS error messages are stored there. This change makes sure that captures errors get stored into document.data-error.
* **54e21ff package-lock needed to cache dependencies in GitHub Workflows.** Installing psychojs into a GitHub Action …
> ENH: some changes in support of automated testing (and one for easier committing)

- README.md
- code-of-conduct.md
Readme:
- needed badge to show our code of conduct (Code Covenant)
- had somewhat outdated notes in a few places
- had its own online status list instead of pointing to the PsychoPy one (hard to maintain both)
> DOCS: Add Code Covenant and update the readme

- CONTRIBUTING.md
- package.json
This guide is based on the improvements I made to the [PsychoPy contributing guide](https://github.com/tpronk/psychopy/blob/improve_CONTRIBUTING/CONTRIBUTING.md). There are a couple of differences though:
* We don't have a dev and release branch, so I suggest to base all new branches on master
* Added a reference to our testing repo
* Reduced the number of tags: 
* Merged BF and FF into BF
* Merged NF and ENH into ENH
* Dropped TEST (since all our tests are in a separate repo)
> DOCS: Add contributing guide

- src/data/TrialHandler.js
@apitiot Add a `trialIterator` getter to expose the internal `[Symbol.iterator]()` then made available for step by step calling via `TrialHandler.next()`. Closes #339
Demo:
[pavlovia.org/support/moving-cue &rarr;](https://pavlovia.org/support/moving-cue)
> data/TrialHandler: allow for calling next() like PsychoPy

- src/visual/TextBox.js
Closes #319 and passes each of the tests below:
* Type something in, resize window -> typed text stays
* Type something in, delete it again -> placeholder reappears
* Type something in, delete it again, resize -> placeholder reappears, and stays when resizing
* Type something in, resize, delete it again -> placeholder reappears
* Type something in, resize, delete it again, resize again -> placeholder reappears
> BF: Retain entered text (and placeholder) upon resize

- src/core/GUI.js
@tpronk That warning was there up until 3.2 and went away with the 2020 releases, @apitiot closes #300
> core/GUI: restore warning about required fields

- src/core/PsychoJS.js
PsychoJS itself passes information about errors via the error argument (instead of the message argument). This PR ensures that the error argument is logged in full in the data-error attribute of the body, so that it can be picked up by our e2e tests.
> ENH: Improve logging (of errors thrown by PsychoJS)

- package-lock.json
- package.json
- src/core/PsychoJS.js
This PR contains a number of improvements needed for our automated testing (via GitHub workflows):
- Add version number `2021.2.0` to package.json. Closes #369 
- Log errors captured by `window.onunhandledrejection` into `document.data-error`. Closes #370
- Workaround for [a bug](https://github.com/actions/setup-node/issues/214) in `package-lock.json` files generated by NPM v7. Closes #371
> Make PsychoJS test-ready again

- package-lock.json
- package.json
- src/core/ServerManager.js
@apitiot @tpronk Restoring `createjs.LoadItem()` calls when pushing to the manifest should work as well now, closes #367
> package: bring back PreloadJS and import for side effects in core/ServerManager

- src/data/TrialHandler.js
- src/util/Util.js
This bug-fix consists of modifications to util.shuffle and TrialHandler:
1. `util.shuffle` supports an optional second argument, rng, which defaults to Math.random
2. TrialHandler now has a getter and setter for the seed attrbute. On setting this attribute it constructs a random number generator (rng) using seedrandom and the seed provided. This rng is passed to `util.shuffle` when preparing a sequence with method RANDOM or FULL_RANDOM
The tests of these modifications can be found in: https://github.com/psychopy/psychojs_testing/blob/main/tests/karma_randomization/karma_randomization.js
> BF: Make seedrandom work again

- src/data/TrialHandler.js
- src/data/index.js
This makes it possible to restore the handler's internal state from snapshot
Fixes #386
> added fromSnapshot static method to TrialHandler

- src/core/MinimalStim.js
- src/core/Window.js
- src/visual/Form.js
- src/visual/Slider.js
This accommodates a more standard way of rendering Form in the generated .js code, i.e. form.setAutoDraw(true), rather than the historically correct form.draw()
Fixes #343
> added the notion of dependent stimuli to Slider

- src/data/TrialHandler.js
finished is a property of the snapshot, which corresponds to _finished at the TrialHandler level, hence the need of a getter now that the code generator uses TrialHandler.fromSnapshot, to restore the internal state
> added a getter for finished in TrialHandler

- src/data/TrialHandler.js
- src/util/PsychObject.js
This makes it possible to access those attributes directly from the TrialHandler, like in PsychoPy:
loop = new TrialHandler({ [...] });
[...]
const color = loop['color'];
> getSnapshot / fromSnapshot now also store/restore TrialHandler's trial attributes

- src/data/TrialHandler.js
This ensure that loop.thisTrial['field'] === thisLoop['field']
Fixes #413
> fromSnapshot now creates a global variable for the trial

- src/visual/Slider.js
@apitiot @TEParsons Use identifiers to match [boilerplate output](https://github.com/psychopy/psychopy/blob/release/psychopy/experiment/components/slider/__init__.py#L251), closes #411
> visual/Slider: bring style symbols inline with PsychoPy

- src/index.css
@tpronk @apitiot @RebeccaHirst Closes #435
> css: override ui-dialog inline styles, use percentage height on body

- src/util/Util.js
In Python, we import `numpy.random.choice` as `randchoice`, so this adds an equivalent function to the JS side.
I can then add an alias to the transpiler to replace `randchoice` with `util.randchoice` in Code components :)
> NF: Add `util.randchoice` to mirror Python

- src/visual/FaceDetector.js
- src/visual/ImageStim.js
- src/visual/MovieStim.js
- src/visual/ShapeStim.js
- src/visual/Slider.js
- src/visual/TextBox.js
- src/visual/TextStim.js
In PsychoPy @peircej chose to use clock/compass convention for ori rather than
engineering/maths convention, so +ve changes move clockwise not anti.
A previous change ( f12ccafff3 ) to the setOri function doesn't appear to have any
effect on the stimuli using the current rendering method
> BF: _pixi.rotation should be set to -this._ori to match PsychoPy (clock) ori

- docs/visual_GratingStim.js.html
- package.json
- scripts/build.js.cjs
- src/visual/GratingStim.js
- src/visual/index.js
- src/visual/shaders/circleShader.frag
- src/visual/shaders/crossShader.frag
- src/visual/shaders/defaultQuad.vert
- src/visual/shaders/gaussShader.frag
- src/visual/shaders/radRampShader.frag
- src/visual/shaders/raisedCosShader.frag
- src/visual/shaders/sawShader.frag
- src/visual/shaders/sinShader.frag
- src/visual/shaders/sinXsinShader.frag
- src/visual/shaders/sqrShader.frag
- src/visual/shaders/sqrXsqrShader.frag
- src/visual/shaders/triShader.frag
Introduces `GratingStim.js` which helps to create all kinds of grating stimuli. In this particular PR a Gabor patch is introduced.
How it works:
If `tex` parameter passed in is an image name (which was previously loaded using `psychoJS.serverManager`), the stim creates `PIXI.TilingSprite` for it and displays it.
If `tex` is one of the predefined functions the shader is going to be used that will render necessary function.
Same goes for `mask` parameter.
usage:
```JS
import { core } from './lib/psychojs.js';
const { PsychoJS } = core;
const psychoJSInst = new PsychoJS();
psychoJSInst.openWindow({
fullscr: false,
color: new util.Color([0, 0, 0]),
units: 'height',
waitBlanking: true
});
...
// further, within experiment initialization function
gratingStimInst = new visual.GratingStim({
win : …
```
> Grating stim class implementation

- package.json
- src/core/PsychoJS.js
- src/data/ExperimentHandler.js
- src/data/index.js
An underscore was inadvertently removed from _projectId. It's now back.
> BF issue with projectId field when saving to database

- src/core/MinimalStim.js
- src/core/Window.js
- src/util/Color.js
- src/visual/Form.js
- src/visual/GratingStim.js
- src/visual/shaders/circleShader.frag
- src/visual/shaders/crossShader.frag
- src/visual/shaders/gaussShader.frag
- src/visual/shaders/radRampShader.frag
- src/visual/shaders/raisedCosShader.frag
- src/visual/shaders/sawShader.frag
- src/visual/shaders/sinShader.frag
- src/visual/shaders/sinXsinShader.frag
- src/visual/shaders/sqrShader.frag
- src/visual/shaders/sqrXsqrShader.frag
- src/visual/shaders/triShader.frag
In addition to gamma, introduced capability to change contrast of the entire scene.
Fixed issue with gamma not being applied to the background. This was done by adding a separate solid-color sprite. As a result of that `core/Window.js` now has separate PIXI container for stims. This allows to move them around independently.
Added 2 new methods to `core/Window.js`:
- `addPixiObject()`
- `removePixiObject()`
For gratings added support:
- blend modes
- per grating contrast
- interpolation (currently only img based gratings)
- proper grating coloring
- phase parameter is multiple of function's period
`util/Color.js` extended with `rgbFull()`, which returns RGB triplet in [-1, 1] range.
webGL renderer now requests `high-performance` mode by default, to select more powerful GPU on the system …
> Further GratingStim development.

- src/visual/GratingStim.js
- src/visual/shaders/circleShader.frag
- src/visual/shaders/crossShader.frag
- src/visual/shaders/imageShader.frag
- src/visual/shaders/radRampShader.frag
- src/visual/shaders/raisedCosShader.frag
- src/visual/shaders/sawShader.frag
- src/visual/shaders/sinShader.frag
- src/visual/shaders/sinXsinShader.frag
- src/visual/shaders/sqrShader.frag
- src/visual/shaders/sqrXsqrShader.frag
- src/visual/shaders/triShader.frag
Image based gratings are now also work using a custom shader, which allows to do whatever necessary directly, through the fragment shader code rather than PIXI's tools.
- Added coloring support for image based Gratings
- Added proper support for for alpha channel, so `opacity` field now works as expected
- Texture coordinates for some Grating functions changed, so that the final image can match their PsychoPy counterparts
> Coloring for image based gratings

- src/visual/Slider.js
`pointermove` and `pointerup` events now listened on `window._rootContainer`, slider instance reacts only if `this._markerDragging = true;`, which is set on `pointerdown` event, listened on `_pixi`. This means that dragging and rendering starts as soon as you press anywhere on the slider including labels. Rating is recorded on `pointerup` event.
> Slider: improved pointer events handling

- package.json
- src/core/PsychoJS.js
- src/sound/AudioClipPlayer.js
- src/sound/Sound.js
- src/sound/SoundPlayer.js
- src/sound/TonePlayer.js
- src/sound/TrackPlayer.js
Previously, changing the value of a Sound required the instantiation of a new SoundPlayer.
This is not efficient, especially in situations where values change very rapidly.
This PR addresses this issue.
> ENH Sound values can be changed without instantiating a new SoundPlayer

- src/visual/GratingStim.js
- src/visual/shaders/wgl1/radialShader.frag
Function used in antialiasing of original shader called `fwidth` which defined as sum of the absolute value of derivatives in x and y:
https://registry.khronos.org/OpenGL-Refpages/gl4/html/fwidth.xhtml
In wgl1 however this function is part of OES_standard_derivatives extension:
https://developer.mozilla.org/en-US/docs/Web/API/OES_standard_derivatives
BUT the PIXI version that we're currently using has weird way of going about compiling shader programs, specifically - it uses a separate "test" gl context, which has no clue about applied extensions. Because of that compilation of the shader code fails and no `fwidth` for us to play with.
In order to circumvent this I calculate derivatives manually and then add their absolutes together so that it all could work in default wgl1 context …
> manual derivatives calculation for radial stim;

- src/core/Window.js
Setting `FAIL_IF_MAJOR_PERFORMANCE_CAVEAT` if necessary to cause PIXI to switch to canvas renderer automatically.
> added checkWebGLSupport flag check in openWindow();

- src/core/PsychoJS.js
- src/core/ServerManager.js
- src/util/Clock.js
- src/util/Util.js
- src/visual/Survey.js
It is now possible to add `{'surveyLibrary': true}` as a resource to ensure that the adequate Survey libraries are loaded at the start of the experiment.
`psychoJS.start({ [...] 
resources: [
{'surveyLibrary': true}
]});`
> ENH Survey: better management of vendor libraries

- package.json
Upgrade due to discovered bug in which strings with partial month name in it treated as date. For instance `'nov_image'` get's converted to `{t: 'n', v: 37196, w: '11/1/01'}` instead of `{t: 's', v: 'nov_image'}`.
> xlsx upgrade due to a string parsing bug
